### ISSUE TITLE
I have Error

### ISSUE THREAD

**Issue by frode88** [WisedomChainGroup/java-wisdomcore#69]
Hi.
How to Solve this? Thank you.

ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./wdc.yml", line 24, column 15

**Comment by Salpadding** [comment]
> Hi.
> How to Solve this? Thank you.
> 
> ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
> in "./wdc.yml", line 24, column 15

How is your wdc.yml looks like?

**Comment by frode88** [comment]
2.1. Example format
Just use that. Did some change to the data base user and password.

**Comment by Salpadding** [comment]
> 2.1. Example format
> Just use that. Did some change to the data base user and password.

here is my configure

```yml
version: '2'

services:

  wdc_pgsql_v0.0.3:
    image: wisdomchain/wdc_pgsql
    restart: always
    container_name: wdc_pgsql_v0.0.3
    volumes:
      - /home/sunflower/wisdom/pgsql:/var/lib/postgresql/data
    ports:
      - '5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      WDC_POSTGRES_USER: user1
      WDC_POSTGRES_PASSWORD: password1
      
  wdc_core:
    image: wisdomchain/wdc_core
    ports:
      - '19585:19585'
      - '9585:9585'
    volumes:
      - '/home/myname/wisdom/leveldb:/home/myname/wisdom/leveldb'
      - '/home/myname/wisdom/fast_sync:/home/myname/wisdom/fast_sync'
      - '/home/myname/wisdom/wisdom-genesis-generator.json:/home/myname/wisdom/wisdom-genesis-generator.json'
      - '/home/myname/wisdom/local.yml:/home/myname/wisdom/local.yml'
    entrypoint: 'java -jar /app/app.jar --spring.config.location=classpath:application.properties,/home/myname/wisdom/local.yml'
```

my local.yml:

```yml
spring:
  datasource:
    url: 'jdbc:postgresql://wdc_pgsql_v0.0.3:5432/postgres'
    username: 'user1'
    password: 'password1'

wisdom:
  database:
    type: 'leveldb'
    directory: '/home/myname/wisdom/leveldb'    
  consensus:
    fast-sync:
      directory: '/home/myname/wisdom/fast_sync'
    genesis: '/home/sunflower/wisdom/wisdom-genesis-generator.json'

p2p:
  address: 'wisdom://localhost:9585'
  bootstraps: 'wisdom://120.76.101.153:9585,wisdom://47.74.183.249:9585,wisdom://47.74.216.251:9585,wisdom://39fb7d079f7dc2e7a2b53a5ee2a0b81d39500ba959f9f87e0a930fb0cdc46333@47.74.86.106:9585'


server:
  port: '19585'
```
